/*
 * This file is generated by jOOQ.
 */
package com.example.EvidenNewsAggregator.entities;


import com.example.EvidenNewsAggregator.entities.tables.Articles;
import com.example.EvidenNewsAggregator.entities.tables.Categories;
import com.example.EvidenNewsAggregator.entities.tables.Roles;
import com.example.EvidenNewsAggregator.entities.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class News extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>news</code>
     */
    public static final News NEWS = new News();

    /**
     * The table <code>news.articles</code>.
     */
    public final Articles ARTICLES = Articles.ARTICLES;

    /**
     * The table <code>news.categories</code>.
     */
    public final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>news.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>news.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private News() {
        super("news", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Articles.ARTICLES,
            Categories.CATEGORIES,
            Roles.ROLES,
            Users.USERS
        );
    }
}
